from typing import Protocol

from app.modules.student.models import (
    GapAnalysisRun,
    ProcessingRun,
    ResumeRecord,
    SkillEvidence,
    StudentProfile,
)


class StudentRepository(Protocol):
    async def initialize(self) -> None: ...
    async def create_account(
        self, student_id: str, email: str, password_hash: str, profile: StudentProfile
    ) -> None: ...
    async def account_by_email(self, email: str) -> dict[str, object] | None: ...
    async def profile(self, student_id: str) -> StudentProfile | None: ...
    async def update_profile(
        self, student_id: str, display_name: str | None, target_role_id: str | None
    ) -> StudentProfile | None: ...
    async def next_resume_version(self, student_id: str) -> int: ...
    async def resume_by_hash(self, student_id: str, content_hash: str) -> ResumeRecord | None: ...
    async def create_resume(self, resume: ResumeRecord) -> None: ...
    async def update_resume_status(self, student_id: str, resume_id: str, status: str) -> None: ...
    async def activate_resume(self, student_id: str, resume_id: str) -> None: ...
    async def resumes(self, student_id: str, limit: int) -> list[ResumeRecord]: ...
    async def resume(self, student_id: str, resume_id: str) -> ResumeRecord | None: ...
    async def save_processing(self, run: ProcessingRun) -> None: ...
    async def save_evidence(self, values: list[SkillEvidence]) -> None: ...
    async def evidence(
        self, student_id: str, resume_id: str | None = None
    ) -> list[SkillEvidence]: ...
    async def evidence_item(self, student_id: str, evidence_id: str) -> SkillEvidence | None: ...
    async def decide_evidence(
        self,
        student_id: str,
        evidence_id: str,
        status: str,
        skill_id: str | None,
        skill_name: str | None,
    ) -> SkillEvidence | None: ...
    async def save_gap(self, run: GapAnalysisRun) -> None: ...
    async def gap(self, student_id: str, run_id: str) -> GapAnalysisRun | None: ...
    async def delete_resume_records(self, student_id: str, resume_id: str) -> bool: ...
